### ISSUE TITLE
Select Edge (s)

### ISSUE THREAD

**Issue by mhecker** [HiWiGAns/GraphVonAnsicht#100]
Add the possibility to select an edge (or maybe even: multiple edges?).
The properties of a selected edge shall be displayed in the property view.

**Comment by mhecker** [comment]
this appears to work now, nice! can we close this issue?

**Comment by Lucas-Steinmann** [comment]
I guess so, implemented with ce9b44883ae0b7134ce5030b08495b1ad6657358 .
