### ISSUE TITLE
Property view gets new columns when new graph is opened

### ISSUE THREAD

**Issue by ratefuchs** [HiWiGAns/GraphVonAnsicht#110]
Whenever a new graph is opened, two additional columns are inserted into the property view. They seem to display the same information as the first two columns, though.

**Comment by Lucas-Steinmann** [comment]
I could not replicate this issue. 
I have been able to replicate and hopefully fix the other to issues in the information view.
Is this issue still present?

**Comment by ratefuchs** [comment]
Cannot reproduce in HEAD, seems like one of the other fixes for the information view fixed this issue as well.
