### ISSUE TITLE
"x" button on the group manager doesn't do anything

### ISSUE THREAD

**Issue by ratefuchs** [HiWiGAns/GraphVonAnsicht#119]
When I click that button, I usually expect the window to close.
Solution would by to either try to hide this button somehow, or use the button to close the window (typically cancelling any changes made since last applying the "configuration").

**Comment by Lucas-Steinmann** [comment]
Fixed in 25f7f85cb2af53b1b7792e90f26c5ab037026a7c.

When filterlayoutoptions is merged into master, this will be resolved.
