### ISSUE TITLE
Group colors of different nodes may overlap

### ISSUE THREAD

**Issue by ratefuchs** [HiWiGAns/GraphVonAnsicht#59]
An example from `Control.pdg.graphml` wit two groups:

![group_color_overlap](https://cloud.githubusercontent.com/assets/1158701/17847577/fb0ab30c-684e-11e6-866f-d7bc95f4e8aa.png)

**Comment by Nicolas-Boltz** [comment]
I honestly don't see the need to fix this right now. Making the border of the group coloring smaller would make it nearly undetectable and I think increasing the minimal distance between vertices could be very labor intense or bring up problems that are even harder to fix. @thatUserjm, @heho ?

**Comment by heho** [comment]
no we could do that, but I dont really see the need.

**Comment by heho** [comment]
We can add a minY and minX distance option later
