### ISSUE TITLE
Display fault when selected a vertex and then moving the graph

### ISSUE THREAD

**Issue by Jonas-Meier** [HiWiGAns/GraphVonAnsicht#78]
When marked at least one vertex and then moving the graph in the view some display fault occur.

![guimarkedandmovingbug](https://cloud.githubusercontent.com/assets/19251666/18084197/825930c4-6ea6-11e6-8352-48cbc5c8662b.PNG)

**Comment by Lucas-Steinmann** [comment]
Probably fixed in 0184f84e1d4647f2666a4ce280e1b8ceb40bad6b by using a different CSS style to apply the border.
