### ISSUE TITLE
show interprocedural edges

### ISSUE THREAD

**Issue by mohrm** [HiWiGAns/GraphVonAnsicht#84]
For example, an actual-in node in a caller method may be connected to several formal-in nodes in the respective callees. I would like to have (like in the old graphviewer) little dummy nodes next to actual-in/actual-out/call/entry/formal-in/formal-out nodes on which I can double-click and then jump to the corresponding nodes in the respective callers/callee.

**Comment by thatUserjm** [comment]
Are there any restrictions concerning the amount of "little dummy nodes" that are connected with a single vertex or can they theoretically occur infinite ?

**Comment by mohrm** [comment]
The number of dummy nodes is equal to the number of outgoing parameter-in edges - so no, there is no statically constant limit.
I do not insist on little dummy nodes. I just would like to have a possibility to navigate from an actual node to every adjacent formal node and vice versa. Maybe there is some other kind of selection mechanism which is more practical for large numbers of incident parameter edges.

**Comment by ratefuchs** [comment]
Drawing interprocedural edges and connected dummy vertices seems to work now, so the only thing left to do is to implement the "jumping to the node represented by the dummy" behavior.

**Comment by Jonas-Meier** [comment]
Jumping to the node represented by the dummy and to the corresponding graph is implemented in Branch filterlayoutoptions

**Comment by Jonas-Meier** [comment]
As the branch filterlayoutoptions is merged into master, this feature now works
